CLI:
"Options:\n"
"  -text                    Run in text-only mode\n"
"  -seed [seed]             Set the random number generator's seed\n"
"  -scriptfile [file]       Use [file] instead of the default sequence.txt as a source of blocks for level 0\n"
"  -startlevel [n]          Start game in level [n]\n"
"  -help                    Display this help message\n"
"  -dark                    Change to theme to dark mode\n"

Command:
"Commands:\n"
"  left or a\n"
"  right or d\n"
"  down or s\n"
"  clockwise or e\n"
"  counterclockwise or q\n"
"  levelup \n"
"  leveldown \n"
"  restart\n"
"  norandom \n"
"  random \n"
"  sequence [file]            Executes the sequence of commands found in file\n"
"  I, J, L, etc.              Replace current block with specified block\n"
"  hint                       Suggests a landing place for the current block\n\n"
"  auto                       Start AI"
"  Commands can be shortened (eg. left -> lef)\n"
"  and executed multiple times (eg. 2left)\n\n"
